// Command api-snapshot creates and verifies FluxUI's public ui package API
// snapshot. It intentionally records declarations rather than comments or
// implementation bodies, making public-surface changes explicit in review.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	packageDir := flag.String("package-dir", "ui", "relative directory of the public package")
	output := flag.String("out", "api/ui.snapshot", "snapshot file")
	write := flag.Bool("write", false, "write the generated snapshot")
	check := flag.Bool("check", false, "fail if the committed snapshot differs")
	flag.Parse()

	if *write == *check {
		fatal(errors.New("specify exactly one of -write or -check"))
	}
	snapshot, err := generate(*packageDir)
	if err != nil {
		fatal(err)
	}
	if *write {
		if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
			fatal(fmt.Errorf("create snapshot directory: %w", err))
		}
		if err := os.WriteFile(*output, snapshot, 0o644); err != nil {
			fatal(fmt.Errorf("write snapshot: %w", err))
		}
		return
	}

	committed, err := os.ReadFile(*output)
	if err != nil {
		fatal(fmt.Errorf("read committed snapshot %s: %w", *output, err))
	}
	if bytes.Equal(committed, snapshot) {
		return
	}
	fmt.Fprintf(os.Stderr, "%s is out of date; run go run ./tools/api-snapshot -write\n", *output)
	fmt.Fprintln(os.Stderr, firstDifference(committed, snapshot))
	os.Exit(1)
}

func generate(packageDir string) ([]byte, error) {
	entries, err := os.ReadDir(packageDir)
	if err != nil {
		return nil, fmt.Errorf("read package directory %s: %w", packageDir, err)
	}
	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		files = append(files, filepath.Join(packageDir, entry.Name()))
	}
	sort.Strings(files)
	if len(files) == 0 {
		return nil, fmt.Errorf("no Go source files found in %s", packageDir)
	}

	fset := token.NewFileSet()
	lines := make([]string, 0, 512)
	packageName := ""
	for _, path := range files {
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		if packageName == "" {
			packageName = file.Name.Name
		}
		if file.Name.Name != packageName {
			return nil, fmt.Errorf("package directory %s contains %q and %q", packageDir, packageName, file.Name.Name)
		}
		lines = append(lines, declarations(fset, file)...)
	}
	sort.Strings(lines)

	var output strings.Builder
	output.WriteString("# FluxUI public API snapshot\n")
	output.WriteString("# Package: ")
	output.WriteString(packageName)
	output.WriteString("\n# Generator: tools/api-snapshot\n")
	output.WriteString("# Toolchain policy: Go 1.25.12\n")
	output.WriteString("# Generated by: go run ./tools/api-snapshot -write\n")
	output.WriteString("# Do not edit by hand.\n\n")
	for _, line := range lines {
		output.WriteString(line)
		output.WriteByte('\n')
	}
	return []byte(output.String()), nil
}

func declarations(fset *token.FileSet, file *ast.File) []string {
	lines := make([]string, 0)
	for _, declaration := range file.Decls {
		switch declaration := declaration.(type) {
		case *ast.FuncDecl:
			if declaration.Name.IsExported() {
				lines = append(lines, functionDeclaration(fset, declaration))
			}
		case *ast.GenDecl:
			switch declaration.Tok {
			case token.TYPE:
				for _, spec := range declaration.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if ok && typeSpec.Name.IsExported() {
						lines = append(lines, typeDeclaration(fset, typeSpec, declaration.Doc))
					}
				}
			case token.CONST, token.VAR:
				for _, spec := range declaration.Specs {
					valueSpec, ok := spec.(*ast.ValueSpec)
					if !ok {
						continue
					}
					for _, name := range valueSpec.Names {
						if !name.IsExported() {
							continue
						}
						lines = append(lines, valueDeclaration(fset, declaration.Tok, name, valueSpec.Type, valueSpec.Doc, declaration.Doc))
					}
				}
			}
		}
	}
	return lines
}

func typeDeclaration(fset *token.FileSet, spec *ast.TypeSpec, declarationDoc *ast.CommentGroup) string {
	copy := *spec
	copy.Doc = nil
	copy.Comment = nil
	line := nodeString(fset, &ast.GenDecl{Tok: token.TYPE, Specs: []ast.Spec{&copy}})
	return line + deprecationSuffix(spec.Doc, declarationDoc)
}

func functionDeclaration(fset *token.FileSet, declaration *ast.FuncDecl) string {
	copy := *declaration
	copy.Doc = nil
	copy.Body = nil
	return nodeString(fset, &copy) + deprecationSuffix(declaration.Doc)
}

func valueDeclaration(fset *token.FileSet, tok token.Token, name *ast.Ident, valueType ast.Expr, docs ...*ast.CommentGroup) string {
	spec := &ast.ValueSpec{Names: []*ast.Ident{name}, Type: valueType}
	return nodeString(fset, &ast.GenDecl{Tok: tok, Specs: []ast.Spec{spec}}) + deprecationSuffix(docs...)
}

func nodeString(fset *token.FileSet, node ast.Node) string {
	var output bytes.Buffer
	if err := format.Node(&output, fset, node); err != nil {
		panic(fmt.Sprintf("format API node: %v", err))
	}
	return strings.TrimSpace(output.String())
}

func deprecationSuffix(groups ...*ast.CommentGroup) string {
	for _, group := range groups {
		if group != nil && strings.Contains(group.Text(), "Deprecated:") {
			return " // Deprecated"
		}
	}
	return ""
}

func firstDifference(committed, generated []byte) string {
	oldLines := strings.Split(string(committed), "\n")
	newLines := strings.Split(string(generated), "\n")
	limit := len(oldLines)
	if len(newLines) < limit {
		limit = len(newLines)
	}
	for index := 0; index < limit; index++ {
		if oldLines[index] != newLines[index] {
			return fmt.Sprintf("first difference at line %d: committed=%q generated=%q", index+1, oldLines[index], newLines[index])
		}
	}
	return fmt.Sprintf("snapshot line count differs: committed=%d generated=%d", len(oldLines), len(newLines))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "api-snapshot:", err)
	os.Exit(1)
}
